name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        package:
          - carify
          - html
          - get-or-create
          - sql-storage
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - run: pnpm install
        working-directory: ${{ matrix.package }}
      - run: pnpx jsr publish
        working-directory: ${{ matrix.package }}
